# Generated by Django 5.0.1 on 2024-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
