# Generated by Django 5.0.1 on 2024-01-20 07:26

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book_on_sale'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('in_stock_books', django.db.models.manager.Manager()),
            ],
        ),
    ]
